"""octavo

Revision ID: 8e18a38923f0
Revises: dffad8d8ce6b
Create Date: 2022-11-16 17:30:26.303911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e18a38923f0'
down_revision = 'dffad8d8ce6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('FavoritesPlanets', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'FavoritesPlanets', 'planets', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FavoritesPlanets', type_='foreignkey')
    op.drop_column('FavoritesPlanets', 'planet_id')
    op.drop_table('planets')
    # ### end Alembic commands ###
