"""setptimo

Revision ID: dffad8d8ce6b
Revises: ce4ebca7fa82
Create Date: 2022-11-16 17:28:56.117964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dffad8d8ce6b'
down_revision = 'ce4ebca7fa82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FavoritesPlanets_ibfk_1', 'FavoritesPlanets', type_='foreignkey')
    op.drop_column('FavoritesPlanets', 'planet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FavoritesPlanets', sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('FavoritesPlanets_ibfk_1', 'FavoritesPlanets', 'planets', ['planet_id'], ['id'])
    # ### end Alembic commands ###
